version: '3'
volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - my-network-name
  keycloak:
      container_name: "keycloak"
      image: jboss/keycloak:13.0.1
      restart: on-failure
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - postgres
      networks:
        - my-network-name

  springcloudapigw:
      build: ./
      container_name: "springcloud-api-gw"
      ports:
        - 80:80 # Exposing application port from docker container to the outside
        - 8000:8000 # Debugging purposes

      depends_on:
        - keycloak

      networks:
        - my-network-name

      command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /SpringCloudGW-0.0.1-SNAPSHOT.jar

networks:
  my-network-name:
    driver: bridge
