version: '3'
services:
  app:
    build: ./
    restart: on-failure
    ports:
      - 8080:8080
      - 8000:8000
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /SpringCloudGW-0.0.1-SNAPSHOT.jar